name: Ejercicio7
on:
   push:
      branch: [ main ]
jobs:
   build:
      runs-on: ubuntu-latest
      steps:
      - name: Fecha y hora de ejecución
        run:
         echo "Hola desde el runner de github"
         echo "Fecha y hora: "
         date
         ls 
         echo "Versión de java"
         java -version || echo "Java no instalado"